#include <stdio.h>

#define GRID_SIZE	9

void outasm(int x, int y)
{
	//  each cell occupies 2 bytes in memory. Hence the multiplications here.
	printf("$%02x, ", y * GRID_SIZE * 2 + x * 2 );

//	printf("[%d,%d] ", x, y);
}


int computeNbrs(int x, int y, void (*outfn)(int x, int y))
{
	int X, Y, i, j;

	// Same row
	for (X=0; X<x; X++) {
		outfn(X,y);
	}
	for (X=x+1; X<GRID_SIZE; X++) {
		outfn(X,y);
	}

	// Same column
	for (Y=0; Y<y; Y++) {
		outfn(x,Y);
	}
	for (Y=y+1; Y<GRID_SIZE; Y++) {
		outfn(x,Y);
	}

	// Same cell AND *NOT* already output above
	for (Y = (y/3)*3, j = 0; j < 3; j++,Y++) {
		for (X = (x/3)*3, i = 0; i < 3; i++,X++) {
			if (Y != y && X != x) {
				outfn(X,Y);
			}
		}
	}

	// Same cell *AND* already output above
	for (Y = (y/3)*3, j = 0; j < 3; j++,Y++) {
		for (X = (x/3)*3, i = 0; i < 3; i++,X++) {
			if ((Y == y || X == x) && !(Y == y && X == x)) {
				outfn(X,Y);
			}
		}
	}

	return 0;
}

void printit(int x, int y)
{
	printf("[%d,%d] ",x,y);
}

void test1(void)
{
	printf("4,4: ");
	computeNbrs(4,4,printit);
	printf("\n");
}

int main(int argc, char **argv)
{
	int y,x;
	int testing = 0;

	if (testing) {
		test1();
		return 0;
	}

	printf(";\n; Generated by neighbors.c\n;\n");

	// First the lists of neighbors
	for (y=0; y<GRID_SIZE; y++) {
		for (x=0; x<GRID_SIZE; x++) {
			printf("_nbors_%d_%d: .dw ", x, y);
			computeNbrs(x,y,outasm);
			printf("\n");
		}
	}

	// Now the 9x9 word array pointing to each list
	printf("neighbor_list:\n");
	for (y=0; y<GRID_SIZE; y++) {
		printf("    .dw ");
		for (x=0; x<GRID_SIZE; x++) {
			printf("_nbors_%d_%d, ", x, y);
		}
		printf("\n");
	}

	return 0;
}
